### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.glass.ui.gtk.GtkPlatformFactory

### ISSUE THREAD

**Issue by SanPen** [griddigit/CimPal#7]
Hi, 

I tried to run the .jar file under ubuntu 22.04 with `java -jar CimPal.jar` and I get this:

```
java -jar CimPal.jar
mar. 30, 2023 3:12:09 P. M. com.sun.javafx.application.PlatformImpl startup
ADVERTENCIA: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3ef8f54e'
java.lang.ClassNotFoundException: com.sun.glass.ui.gtk.GtkPlatformFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I have both java and javafx packages installed with openjdk and openjfx.

Thanks

**Comment by griddigit** [comment]
Hello 
do you have Java 11?

Best regards
Chavdar

**Comment by SanPen** [comment]
yes

**Comment by griddigit** [comment]
is this in windows? As I didn't try in other platforms

**Comment by SanPen** [comment]
This would be Ubuntu, I'll try windows later on

**Comment by SanPen** [comment]
Loading workd on windows
